version: '3.4'
services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    ports:
      - "8002:80"
    build:
      context: .
      dockerfile: Employee.WebApp/Dockerfile
  
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    ports:
      - "8003:80"
    build:
      context: .
      dockerfile: Employee.API/Dockerfile
